# Generated by Django 5.0.3 on 2024-04-02 17:44

from django.db import migrations


def seed_operations(apps, schema_editor):
    Operation = apps.get_model('calculator', 'Operation')
    Operation.objects.create(type="addition", cost=3)
    Operation.objects.create(type="subtraction", cost=3)
    Operation.objects.create(type="multiplication", cost=5)
    Operation.objects.create(type="division", cost=5)
    Operation.objects.create(type="square_root", cost=4)
    Operation.objects.create(type="random_string", cost=8)


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_operation_type'),
    ]

    operations = [
        migrations.RunPython(seed_operations),
    ]
