# Generated by Django 5.0.3 on 2024-04-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.IntegerField(default=2500),
        ),
    ]
