# Generated by Django 5.0.3 on 2024-04-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_record_deleted_at_alter_userprofile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
