# Generated by Django 5.0.3 on 2024-04-18 12:50

from django.db import migrations
from calculator.models import Operation


def update_operations_name(apps, schema_editor):
    operations = [
        ('addition', 'Addition'),
        ('subtraction', 'Subtraction'),
        ('multiplication', 'Multiplication'),
        ('division', 'Division'),
        ('square_root', 'Square Root'),
        ('random_string', 'Random String')
    ]

    for operation_type, operation_name in operations:
        try:
            operation = Operation.objects.get(type=operation_type)
            # Update the name
            operation.name = operation_name
            operation.save()
        except Operation.DoesNotExist:
            print(f"No operation found for type {operation_type}")
        except Exception as e:
            print(f"Error updating operation {operation_type}: {str(e)}")


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_populate_operations_and_user'),
    ]

    operations = [
        migrations.RunPython(update_operations_name),
    ]
