# Generated by Django 5.0.3 on 2024-04-18 23:43

from django.db import migrations
import random
from django.contrib.auth.models import User
from calculator.models import Record, Operation


def seed_user_no_balance(apps, schema_editor):
    new_user = User.objects.create(username='testuser2')
    new_user.set_password('123qweasd')
    new_user.save()

    user_profile = new_user.userprofile

    # Create a thousand random records
    operations = Operation.objects.all()
    for _ in range(179):
        operation = random.choice(operations)

        record = Record.objects.create(
            user=new_user,
            operation=operation,
            amount=operation.cost,
            user_balance=user_profile.balance - operation.cost,
            operation_response=random.randint(1, 100)
        )

        # Calculate new balance after each operation
        user_profile.balance = record.user_balance
        user_profile.save()

    user_profile.balance = 1
    user_profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_update_operations_name'),
    ]

    operations = [
        migrations.RunPython(seed_user_no_balance)
    ]
